services:
  server:
    build:
      context: ./server
      dockerfile: DockerFile
    deploy:
      replicas: 2
    volumes:
      - ./server:/src
      - /src/node_modules
    env_file:
      - ./server/.env      
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - KAFKA_BROKER=broker:29092
    depends_on:
      - broker

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: deadlink-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env       
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: /src/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
      - client

  broker:
    image: confluentinc/confluent-local:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT'
